/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void buttonLoad_click(GButton source, GEvent event) { //_CODE_:buttonLoad:968751:
  println("buttonLoad - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonLoad:968751:

public void buttonBlack_click(GButton source, GEvent event) { //_CODE_:buttonBlack:450674:
  println("buttonBlack - GButton >> GEvent." + event + " @ " + millis());
  currentMode = drawMode[0];
  stroke(0);
  strokeWeight(2);
} //_CODE_:buttonBlack:450674:

public void buttonCable_click(GButton source, GEvent event) { //_CODE_:buttonCable:555797:
  println("buttonCable - GButton >> GEvent." + event + " @ " + millis());
   currentMode = drawMode[1];
   stroke(255,0,0);
   strokeWeight(2);
} //_CODE_:buttonCable:555797:

public void buttonSave_click(GButton source, GEvent event) { //_CODE_:buttonSave:329439:
  println("buttonSave - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonSave:329439:

public void buttonHMeas_click(GButton source, GEvent event) { //_CODE_:buttonHMeas:946616:
  println("buttonHMeas - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonHMeas:946616:

public void buttonVMeas_click(GButton source, GEvent event) { //_CODE_:buttonVMeas:242293:
  println("buttonVMeas - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonVMeas:242293:

public void buttonPed_click(GButton source, GEvent event) { //_CODE_:buttonPed:726158:
  println("buttonPed - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonPed:726158:

public void buttonPole_click(GButton source, GEvent event) { //_CODE_:buttonPole:477460:
  println("buttonPole - GButton >> GEvent." + event + " @ " + millis());
  
} //_CODE_:buttonPole:477460:

public void buttonTX_click(GButton source, GEvent event) { //_CODE_:buttonTX:300968:
  println("buttonTX - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonTX:300968:

public void buttonVault_click(GButton source, GEvent event) { //_CODE_:buttonVault:341235:
  println("buttonVault - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonVault:341235:

public void buttonItem_click(GButton source, GEvent event) { //_CODE_:buttonItem:746836:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonItem:746836:

public void buttonErase_click(GButton source, GEvent event) { //_CODE_:buttonErase:949974:
  println("buttonErase - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonErase:949974:

public void buttonHLabel_click(GButton source, GEvent event) { //_CODE_:buttonHLabel:804713:
  println("buttonHLabel - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonHLabel:804713:

public void buttonVLabel_click(GButton source, GEvent event) { //_CODE_:buttonVLabel:761865:
  println("buttonVLabel - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonVLabel:761865:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Draw");
  buttonLoad = new GButton(this, 0, 0, 50, 40);
  buttonLoad.setText("Load LB");
  buttonLoad.addEventHandler(this, "buttonLoad_click");
  buttonBlack = new GButton(this, 70, 0, 50, 40);
  buttonBlack.setText("Black Line");
  buttonBlack.addEventHandler(this, "buttonBlack_click");
  buttonCable = new GButton(this, 140, 0, 50, 40);
  buttonCable.setText("Cable Line");
  buttonCable.addEventHandler(this, "buttonCable_click");
  buttonSave = new GButton(this, 0, 60, 50, 40);
  buttonSave.setText("Save Image");
  buttonSave.addEventHandler(this, "buttonSave_click");
  buttonHMeas = new GButton(this, 70, 60, 50, 40);
  buttonHMeas.setText("Horiz Meas");
  buttonHMeas.addEventHandler(this, "buttonHMeas_click");
  buttonVMeas = new GButton(this, 140, 60, 50, 40);
  buttonVMeas.setText("Vert Meas");
  buttonVMeas.addEventHandler(this, "buttonVMeas_click");
  buttonPed = new GButton(this, 210, 0, 50, 40);
  buttonPed.setText("Ped");
  buttonPed.addEventHandler(this, "buttonPed_click");
  buttonPole = new GButton(this, 280, 0, 50, 40);
  buttonPole.setText("Pole");
  buttonPole.addEventHandler(this, "buttonPole_click");
  buttonTX = new GButton(this, 350, 0, 50, 40);
  buttonTX.setText("TX");
  buttonTX.addEventHandler(this, "buttonTX_click");
  buttonVault = new GButton(this, 420, 0, 50, 40);
  buttonVault.setText("Vault");
  buttonVault.addEventHandler(this, "buttonVault_click");
  buttonItem = new GButton(this, 420, 60, 50, 40);
  buttonItem.setText("Item");
  buttonItem.addEventHandler(this, "buttonItem_click");
  buttonErase = new GButton(this, 210, 60, 50, 40);
  buttonErase.setText("Erase");
  buttonErase.addEventHandler(this, "buttonErase_click");
  buttonHLabel = new GButton(this, 280, 60, 50, 40);
  buttonHLabel.setText("Horiz Label");
  buttonHLabel.addEventHandler(this, "buttonHLabel_click");
  buttonVLabel = new GButton(this, 350, 60, 50, 40);
  buttonVLabel.setText("Vert Label");
  buttonVLabel.addEventHandler(this, "buttonVLabel_click");
}

// Variable declarations 
// autogenerated do not edit
GButton buttonLoad; 
GButton buttonBlack; 
GButton buttonCable; 
GButton buttonSave; 
GButton buttonHMeas; 
GButton buttonVMeas; 
GButton buttonPed; 
GButton buttonPole; 
GButton buttonTX; 
GButton buttonVault; 
GButton buttonItem; 
GButton buttonErase; 
GButton buttonHLabel; 
GButton buttonVLabel; 
